- src/Materializer/DynamicMethodModelFactory.cs
- tests/Kros.KORM.UnitTests/Integration/LinqTests.cs
- tests/Kros.KORM.UnitTests/Materializer/MethodModelFactoryShould.cs
> Fix bug #9

- README.md
- build.yml
> Added build status from Azure DevOps.

- src/CommandGenerator/CommandGenerator.cs
- src/Converter/ConverterHelper.cs
- tests/Kros.KORM.UnitTests/CommandGenerator/CommandGeneratorShould.cs
Closes #19 
First commit is just a cleanup. Real fix is in the second commit.
> Converter is used for null values

- src/Converter/NullAndTrimStringConverter.cs
- src/Properties/Resources.Designer.cs
- src/Properties/Resources.resx
- tests/Kros.KORM.UnitTests/Converter/NullAndTrimStringConverterShould.cs
> WIP NullAndTrimStringConverter

- src/Database.DatabaseBuilder.cs
- src/Kros.KORM.csproj
> Fixed bug in DatabaseBuilder

- src/Migrations/MigrationsRunner.cs
- tests/Kros.KORM.UnitTests/Migrations/MigrationsRunnerShould.cs
- `MigrationsRunner` is `IDisposable`
- `MigrationsRunner` also accepts just connection string to database in its constructor (not the `IDatabase` instance).
> MigrationsRunner is IDisposable

- README.md
> Add 'Value generators` to TOC of readme

- src/Database.cs
- src/IDatabase.cs
- src/IDatabaseExtensions.cs
- src/Query/DbSet.cs
- src/Query/IDbSet.cs
- src/Query/Providers/IQueryProvider.cs
- src/Query/Providers/QueryProvider.cs
- tests/Kros.KORM.UnitTests/Integration/IDatabaseExtensionsShould.cs
- tests/Kros.KORM.UnitTests/Query/DbSetShould.cs
- tests/Kros.KORM.UnitTests/Query/Providers/QueryProviderShould.cs
> Added cancellationToken parameter to async functions.

- src/Migrations/MigrationOptions.cs
- src/Migrations/MigrationsRunner.cs
> Added options for migration script timeout

- src/Kros.KORM.csproj
- src/Properties/Resources.Designer.cs
- src/Properties/Resources.resx
- src/Query/DbSet.cs
> Support for composite primary key in bulk update.

- README.md
- src/CommandGenerator/CommandGenerator.cs
- src/CommandGenerator/ICommandGenerator.cs
- src/Kros.KORM.csproj
- src/Properties/Resources.Designer.cs
- src/Properties/Resources.resx
- src/Query/DbSet.cs
- tests/Kros.KORM.UnitTests/CommandGenerator/CommandGeneratorShould.cs
implemnets upsert command by using merge sql command ([documentation](https://docs.microsoft.com/en-us/sql/t-sql/statements/merge-transact-sql?view=sql-server-ver15), [upsert usage](https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/implementing-merge-functionality-in-a-natively-compiled-stored-procedure?view=sql-server-ver15))
> upsert command

- src/Query/IDbSet.cs
Upsert method was implemented in DbSet but not described in IDbSet interface
> idbset upsert

- src/Materializer/RecordModelFactory.cs
- src/Properties/Resources.Designer.cs
- src/Properties/Resources.resx
- tests/Kros.KORM.UnitTests/Materializer/MethodModelFactoryForRecordShould.cs
Check if constructor parameter match property.
> Check if ctor param match property

- src/CommandGenerator/CommandGenerator.cs
- src/Metadata/TableInfo.cs
- tests/Kros.KORM.UnitTests/CommandGenerator/CommandGeneratorShould.cs
- tests/Kros.KORM.UnitTests/Integration/TriggerTests.cs
Closes #76 
Changet insert command as:
```SQL
DECLARE @OutputTable TABLE (columns...);
INSERT INTO table (columns...) OUTPUT INSERTED.Id, ... INTO @OutputTable VALUES (values...);
SELECT * FROM @OutputTable;
```
> Use output into in isnsert commmand.

- README.md
- src/CommandGenerator/CommandGenerator.cs
- src/CommandGenerator/ICommandGenerator.cs
- src/Properties/Resources.Designer.cs
- src/Properties/Resources.resx
- src/Query/DbSet.cs
- src/Query/IDbSet.cs
- src/ThrowHelper.cs
- tests/Kros.KORM.UnitTests/CommandGenerator/CommandGeneratorShould.cs
- tests/Kros.KORM.UnitTests/Integration/DbSetShould.cs
adds ability to define custom columns to match in upsert command.
These are configured via `WithCustomUpsertConditionColumns` method on IDbSet
> custom columns condition in upsert command 

- README.md
- src/Extensions/TypeExtensions.cs
- src/IDatabaseExtensions.TempTable.cs
- src/IDatabaseExtensions.cs
- src/Kros.KORM.csproj
- src/Properties/Resources.Designer.cs
- src/Properties/Resources.resx
- tests/Kros.KORM.UnitTests/Extensions/TypeExtensionsShould.cs
- tests/Kros.KORM.UnitTests/Integration/IDatabaseExtensionsShould.cs
- tests/Kros.KORM.UnitTests/Integration/IDatabaseExtensionsTempTableShould.cs
Added execute with temp table extension for IDatabase.
#81 issue resolved
> Added execute with temp table extension for IDatabase.

- src/Database.cs
- src/Kros.KORM.csproj
- tests/Kros.KORM.UnitTests/Integration/DbSetGuidPrimaryKeyTests.cs
Closes #87 
Technicky v KORM-e nie je nič potrebné, pretože sa to rieši GUID generátorom, ktorý je v `Kros.Utils`, takže aj v klientskom projekte stačí aktualizovať tú knižnicu. Pridal som tu však testy na to.
> Add support for GUID primary keys

- src/Data/TransactionHelper.cs
- src/IDatabaseExtensions.TempTable.cs
- src/Kros.KORM.csproj
> Execute with temp table extension with command timeout.

- README.md
- src/Query/Sql/DefaultQuerySqlGenerator.cs
- tests/Kros.KORM.UnitTests/Query/Sql/DefaultQuerySqlGeneratorShould.cs
Added string comparison using `string.Compare(string, string)` to where condition in SQL query. Also unit tests for use of string methods in SQL query are added.
> String comparison in SQL query

- src/Query/Sql/DefaultQuerySqlGenerator.cs
- tests/Kros.KORM.UnitTests/Query/Sql/LinqFunctionTranslatorShould.cs
Closes #105 
Adds unit tests for LongCount method.
> Unit tests for LongCount method

- src/KormConnectionSettings.cs
- src/Kros.KORM.csproj
Add application name parameter to KormConnectionSettings to enable setting application parameter in connection string.
> add ApplicationName to KormConnectionSettings
